version: '3'
services:
  web:
    container_name: laravel-docker
    volumes:
      - "./:/app"
    build: .
    ports:
      - "8000:8000"
    networks:
      laravel_docker:
        ipv4_address: 192.50.56.199

        networks:
  laravel_docker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.50.56.0/24
