version: '3'
services:
  web:
    container_name: laravel-docker
    volumes:
      - "./:/app"
    build: .
    ports:
      - "8000:8000"
    networks:
      laravel_docker:
        ipv4_address: 192.50.56.199
    links:
      - database
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: laravel-docker-database
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      laravel_docker:
        ipv4_address: 192.50.56.200

networks:
  laravel_docker:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.50.56.0/24
